name: Run tests with maven
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      petstore-api:
        image: swaggerapi/petstore3:latest
        ports:
          - 8080:8080
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run tests
        run: mvn test